#! /bin/sh
#
# System-V init script for the openntp daemon
#

. /etc/sysconfig/system_vars
if [ "$NTP_ENABLED" == "N" ]; then
	exit 0
fi
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="network time protocol daemon"
NAME=ntpd
DAEMON=/usr/sbin/$NAME
SERVERS=`cat /etc/ntp.conf | grep server | sed 's/server //g' | sed 's/ iburst//g'`

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Read config file if it is present.
if [ -r /etc/default/$NAME ]; then
	. /etc/default/$NAME
fi

case "$1" in
  start)
	echo -n "Starting $DESC: $NAME"
	start-stop-daemon -S -q -x $DAEMON -- -g -p $SERVERS
	echo "."
	;;
  stop) echo -n "Stopping $DESC: $NAME"
	start-stop-daemon -K -q -n $NAME
	echo "."
	;;
  reload|force-reload) echo -n "Reloading $DESC configuration..."
	start-stop-daemon -K -q -n $NAME -s 1
	echo "done."
  ;;
  restart) echo "Restarting $DESC: $NAME"
	$0 stop
	sleep 1
	$0 start
	;;
  *) echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
