#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	echo -n "Starting sshd: "
	if [ ! -f /etc/ssh/ssh_host_key ]; then
		mount /dev/mmcblk0p3 /mnt
		/usr/bin/ssh-keygen -A
		cp -r /etc/ss* /mnt/sysconfig/etc/.
		umount /mnt
	fi
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	echo -n "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

